### ISSUE TITLE
maps?

### ISSUE THREAD

**Issue by Driesboy** [majovec/MINETOX-GAMETEAM-ALL-PLUGINS-OLD-#2]

**Comment by majovec** [comment]
google easy ...

**Comment by Driesboy** [comment]
in the descriptuon plugins +
where are the maps?

Op 3-jan.-2017 20:29 schreef "majovec" <notifications@github.com>:

**Comment by majovec** [comment]
you download from planet minecraft or youtube or google .... idiots ....

**Comment by Driesboy** [comment]
IQJSDKLJQSKLDFJ
